- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
- test/editor_test.cpp
- test_data/crossdoor_with_subtree.xml
- test_data/test_files.qrc
- test_data/test_xml_key_reordering_issue.xml
This PR fixes a random reordering of keys in the xml output file that happens each time the file is saved from a new Groot process, even if no changes were made to the tree. 
The issue can be replicated by creating a tree description xml file that has nodes with multiple input or output ports (the `test_data/test_xml_key_reordering_issue.xml` included in this PR, for instance). Open Groot, load the file and save a copy of it. Close and start Groot again, open the file again a save a second copy. Then compare the original with both copies using `diff`; there should be differences in the ordering of xml attributes.
This becomes an issue when the xml file is stored in a version control system such as git.
The random reordering happens because newer versions of the `QDomDocument` uses …
> Stop using QDomDocument::toString to avoid QHash random reordering

- bt_editor/mainwindow.cpp
System crashes when edit tree with the same name because of : 
`_tab_info.erase( prev_ID )`
It also solves the problem in issue #43 
-----------
Test 1:
- Add SubTree with Name T 
- right-click on T and Edit (on Palette), 
- Do not change anything and press "OK". 
- Try to expand the Tree (it crashes before)
Test 2:
- Add SubTree with Name T 
- right-click on T and Edit (on Palette),
- Add Port and Ok.
- Expand it (it crashes before)
> fix "renaming" subtree with the same previous name

- bt_editor/sidepanel_monitor.cpp
I create several trees in my ros node by BehaviorTreeCpp. When i monitor first with Groot, it works fine, but if i try to monitor second tree, Groot crushes with std::out_of_range.
Adding remapping uid to index solved the problem.
> fix uid remapping for monitor mode

- bt_editor/models/BehaviorTreeNodeModel.cpp
Can't see text of port description tooltip. Changing text style solved the problem.
(don't know how to make screenshort with tooltip)
> change tooltip color to make it differ from background and visible

- package.xml
Add the following dependency names of ROS index:
- qtbase5-dev https://index.ros.org/d/qtbase5-dev/
- libqt5-svg-dev https://index.ros.org/d/libqt5-svg-dev/
- libqt5-opengl-dev https://index.ros.org/d/libqt5-opengl-dev/
- qttools5-dev-tools https://index.ros.org/d/qttools5-dev-tools/
- libdw-dev https://index.ros.org/d/libdw-dev/
- libzmq3-dev https://index.ros.org/d/libzmq3-dev/
This adds all dependencies mentioned in `Readme.md` and `.travis.yaml`
> Add build dependencies, Format package.xml, closes #77

- bt_editor/sidepanel_editor.cpp
I didn't see any QT flags for disabling the context menu, so on each menu click I just loop through _tree_view_category_items and check if the value is found.  If found I block the context menu.
Note I am branching from e4863d5 as this is the latest version that builds (for travis)
> proposed fix for #87

- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
- bt_editor/sidepanel_replay.cpp
- bt_editor/sidepanel_replay.h
- bt_editor/utils.cpp
- bt_editor/utils.h
If tree don't have any running node, we can see nothing about deep nodes in monitor mode, only upper node state. 
We can avoid the problem by increasing tick frequency, but it requires more computational resourses.
My solution is adding graphical styles for IDLE nodes, that was SUCCESS or FAILURE at current tick. 
Gray-green - it is a IDLE status, that was SUCCESS in the past of the tick.
Gray-red - IDLE, that was FAILURE.
I.e. nodes stores it's last previous state and shows it, if current state is IDLE.
It is also works well with RUNNING status
and in replay mode
> Feature idle trail

- bt_editor/sidepanel_editor.cpp
- bt_editor/sidepanel_replay.cpp
Checks for obvious errors in the log flatbuffer file and gives correct warning.  Also fixed a typo 'form' -> 'from'
> Fix Issue 95

- bt_editor/sidepanel_monitor.cpp
Hey,
@facontidavide Thanks for merging #61 ! I had a little thing to add to this to make it work in more usecases (reconnect while the bt changed in nav2 and other manually testable corner cases).
So for reference I made the first commit identical to the new old PR of the PR..
I then saw the problems why you choose to include #61 manually (file conflicts), so I redid my PR and put it into smaller commits. This way it should be pretty straight forward.
With this now, nav2 is pretty much good to go to use Groot! :) 
Ref to nav2-PR: https://github.com/ros-planning/navigation2/pull/1958
> Small Fix for Reloading Tree from #61

- bt_editor/custom_node_dialog.cpp
Fix for issue #99
**Description**
---
When the node is edit mode, depending on the node type the combo box index is set and the curentIndexChanged callback where `checkValid()` is called. Inside `checkValid()` node name is validated using RegExpValidator `_validator` which is created later in the constructor using the `new` operator.
**Fix**
---
Reordered QRegExpValidator so that it is created before the edit logic is executed.
**Tested on**
---
Ubuntu 20, Master branch of Groot and BehaviorTree.CPP
> Fix crash on node edit

- CMakeLists.txt
- package.xml
Signed-off-by: Alexander Xydes <alexander.xydes@navy.mil>
Standalone compiling and ROS 1 workspaces are still supported as well.
> Add support for compiling Groot in ROS 2 workspaces.

- bt_editor/graphic_container.cpp
- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
- bt_editor/sidepanel_monitor.cpp
- bt_editor/sidepanel_monitor.h
- bt_editor/sidepanel_replay.cpp
- bt_editor/sidepanel_replay.h
I was able to fix the majority of edits which cause crashes in log replay and monitor mode.  Not sure if this is the correct way to lock nodes. I had to call `dynamic_cast<MainWindow*>` in a few places to get this to work
> Fix for Issue #101

- bt_editor/mainwindow.cpp
Solves segfaults from #52 and #111 
One problem was caused by attempting to expand invalid subtrees, e.g., with an unconnected node. This change gives a popup message saying that this subtree can not be expanded.
Another problem was when a subtree was already expanded, and then modified into an invalid subtree, e.g., by removing an edge. Switching back to the tab with the expanded subtree triggered code to refresh the now invalid subtree leading to a segfault. This change collapses the subtree before refreshing it.
> Solve segfaults caused by expanding / refreshing invalid subtrees

- bt_editor/sidepanel_editor.cpp
Let default foreground colors for read-only items.
Better shade of blue for editable items.
Fixes #154.
> Better colors for palette items

- CMakeLists.txt
I noticed that it was not possible to compile Groot if I didn't want to download BT as submodule, although I had it installed on the system. The name of the library was wrong in the find_package(...) command.
> Fixed linking with BehaviorTrees already installed on the system.

- bt_editor/graphic_container.cpp
Idle trail styles was broken after 5deaf8533a33771712d4f8caee834e72bbcf9b52
before fix
after fix
I checked expanding, collapsing, adding subtrees in edit mode - seems no problems
> fix node style for idle trail

- bt_editor/mainwindow.cpp
I noticed the output xml always contained an extra (so two) line ending at the end of the file.
Since I have got a git-checker enabled for that, it anoyed me slightly. This fixes the double line-ending.
> No need for line ending as the xml_text already contains it

- bt_editor/mainwindow.cpp
I kinda misunderstood  the whole SubTree building which resulted in me getting a segmentation fault. To make it easier to debug for others I added a warning dialog instead of crashing with a segfault.
* Checked for nullptr after calling getTabByName in subTreeExpand and presenting warning dialog in case SubTree was not found.
> Added check for nullptr when expanding SubTree

- bt_editor/resources/NodesStyle.json
- test_data/Simple.xml
- test_data/crossdoor_with_subtree.xml
- test_data/show_all.xml
Same as https://github.com/BehaviorTree/BehaviorTree.CPP/pull/308 but for Groot.
Fixes the `editor_test` and also adds the little icon as below:
before:
after:
> Fix references to RetryUntilSuccesful

- QtNodeEditor/src/NodeState.cpp
- bt_editor/sidepanel_monitor.cpp
This cleans up these gcc warnings, mostly related to moving to the newer API of zmq vs. deprecated function use:
```bash
NodeState.cpp:51:34: warning: comparison of integer expressions of different signedness: ‘QtNodes::PortIndex’ {aka ‘int’} and ‘std::vector<std::unordered_map<QUuid, QtNodes::Connection*> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
51 |   if( portIndex < 0 || portIndex >= connections.size() )
sidepanel_monitor.cpp:42:42: warning: ‘bool zmq::detail::socket_base::recv(zmq::message_t*, int)’ is deprecated: from 4.3.1, use recv taking a reference to message_t and recv_flags [-Wdeprecated-declarations]
42 |         while(  _zmq_subscriber.recv(&msg) )
sidepanel_monitor.cpp:1:
/usr/include/zmq.hpp:1407:10: note: declared here
1407 |     bool recv(message_t *msg_, …
```
> Cleaning up minor warnings

- bt_editor/XML_utilities.cpp
The following previous PR changed the signature of `BT::VerifyXML` to take an `unordered_map` instead of `std::set`.
https://github.com/BehaviorTree/BehaviorTree.CPP/pull/424
But Groot still uses the old signature in [XML_utilities.cpp](https://github.com/BehaviorTree/Groot/blob/master/bt_editor/XML_utilities.cpp#L185-L205).
This PR updates Groot so that it compiles with BehaviorTreeCPP 3.8.
BTW, very looking forward to see Groot2 :)
> Fix compilation issue when using groot with BehaviorTreeCpp v3.8

- CMakeLists.txt
On macOS, `zmq.hpp` comes from a separate package -- cppzmq. So in order to build on macOS, cppzmq needs to be linked in, not plain zmq. This change fixes this build on macOS (shouldn't impact anything else).
> Fix build on macOS

- CMakeLists.txt
When compiling on ROS1 but using colcon, catkin was not being detected.
This adds a check for catkin similar to the way it's done for ament in addition to the other checks.
> added a check for catkin similar to ament to fix colcon on ROS1

- test/CMakeLists.txt
This fixed broken unit tests (at least on Ubuntu 20.04 using CMake 3.16.3) with the following output:
```bash
Unable to find executable: COMMAND
Unable to find executable: COMMAND
Errors while running CTest
```
I believe the change should be compatible with all recent version of CMake, though I have not broadly tested it.
> Fixed CMake command API error.

- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
Adding a showEvent to centralize view after opening Groot.
Before:
After:
> Recenter view and set focus when initialized

- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
- bt_editor/sidepanel_editor.cpp
- bt_editor/sidepanel_editor.h
If there are many sub-trees in a given unified tree, it is difficult to navigate the tab bar. This PR adds functionality to change the active tab in the tab bar if a user double-clicks on the sub-tree in the side panel.
> Change tab scope if the user double-clicks on a subtree

- package.xml
CMakeLists.txt calls out `ament_index_cpp` but does not include it in the `package.xml` .
> Add missing dep to package.xml

- bt_editor/main.cpp
- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
- bt_editor/sidepanel_monitor.cpp
- bt_editor/sidepanel_monitor.h
- bt_editor/sidepanel_monitor.ui
This PR adds some extra options to Groot to configure the BT monitor to start with specific address and publisher/server ports, as well as automatically connect by "clicking" the Connect button in the code, if enabled.
Specifically, it lets us run Groot as follows:
```
ros2 run groot Groot --mode monitor --address 192.168.1.42 --publisher_port 1668 --server_port 1669 --autoconnect
```
The `autoconnect` option effectively does the following:
- Increases the timeout for the ZMQ subscriber to 10 seconds
- Triggers a click of the "Connect" button in code
- The above resets the timeout to the default 1 second for users to manually connect/disconnect with the normal timeout
This addresses https://github.com/BehaviorTree/Groot/issues/133 and https://github.com/BehaviorTree/Groot/issues/166.
> Add publisher/server and autoconnect args to BT Monitor

- CMakeLists.txt
Modern Linux distributions ship ncurses, but not curses. Not all alias the latter to the former.
> Link with ncurses instead of curses

- bt_editor/graphic_container.cpp
- bt_editor/graphic_container.h
- bt_editor/main.cpp
- bt_editor/mainwindow.cpp
- bt_editor/mainwindow.h
- bt_editor/mainwindow.ui
After #186 
Addressing my own comment: https://github.com/BehaviorTree/Groot/issues/152#issuecomment-1248010342
> Feature: Add commandline options of editor file and svg output
